### PR TITLE
Task form layout

### PR DESCRIPTION
**Pull request by elainamhill**
Commit Notes: 

- _Change name of “asset” folder to “assets” (did not catch this at code review) and renamed “CSS” folder to “css” (lower-case for best practice)_

- _Add “img”, “font”, and “js” folders to “assets” for future use and format “style.css”_

- **Place task form headers inside input label elements**

- **Fix due date alignment with date picker:** previously “Due Date” was not aligned with its date selector without `</br>` being included (label and input had conflicting id tags)

- **Adjust “Add Task” button layout**: button is now full-width and completely aligned with form (removed in-line styling, added a nested `<div>` and set class to “d-grid”)

- **Change site title, main header, and “Add new task” section names**: title and main header “Task List” renamed to “Task Planner”; section “Add New Task” renamed to “New Task” 
  
- **Removed in-line styling for “Add Task” form button** and added class “.btn-primary” to CSS file for bold font text on buttons

### CODE REVIEW

**Review by pknisher11 — DISMISSED** [review]
Please remove the **Task Planner title** that is not required

The due date has to be aligned **aside** the "**assigned to  box**" 

You have to remove the extra "add task" button, **only one button required**

Also remove the **Add New Task title**

But besides that it is correct.

**Comment by elainamhill** [comment]
**I appreciate your feedback Pathik, I'll address these:**

> Please remove the **Task Planner title** that is not required

You're correct, this is not required - however, I feel that a large portion of this project requires us to use our creativity and make the site our own. Right now, ours is just a direct copy of the final project example posted in the instructions. **I'd like Coletha and Wilgens to also view this change to see what they think.**

> The due date has to be aligned **aside** the "**assigned to box**"

With my changes, the Due Date is still aligned with the Assign To box. They are side-by-side. It was the header/label of the Due Date box that was not correctly aligned above the date picker. 

> You have to remove the extra "add task" button, **only one button required**

There is no extra Add Task button, just one (the original) with some formatting changes. 

> Also remove the **Add New Task title**

Same feedback as above - we should feel free to use our discretion here as long as rubric requirements are being met.

**Review by colethab — APPROVED** [review]
Didn't realize I had an issue with the font case. Thank you for correcting that. As mentioned earlier I a fine with the changes.

**Comment by walmonor** [comment]
I am fine with the changes as well...

**Pull request merged**
